-- Systematic point-in-time primary event evidence for Oversold Reversion.

create table if not exists public.or_primary_evidence (
  id bigint generated by default as identity primary key,
  candidate_id bigint not null references public.or_candidates(id) on delete cascade,
  evidence_snapshot_id bigint not null references public.or_evidence_snapshots(id) on delete cascade,
  scan_id uuid not null references public.or_scans(id) on delete cascade,
  symbol text not null,
  source_kind text not null check (
    source_kind in ('sec_filing','clinical_trial_registry','fda_regulatory_record')
  ),
  source_authority text not null,
  external_id text not null,
  accession_number text,
  form text,
  accepted_at timestamptz,
  filed_date date,
  available_at timestamptz not null,
  evidence_cutoff timestamptz not null,
  title text not null,
  source_url text not null,
  summary text,
  content_excerpt text,
  content_hash text not null,
  documents jsonb not null default '[]'::jsonb,
  metadata jsonb not null default '{}'::jsonb,
  retrieved_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  constraint or_primary_evidence_cutoff_check check (available_at <= evidence_cutoff),
  constraint or_primary_evidence_snapshot_source_key
    unique (evidence_snapshot_id, source_kind, external_id)
);

alter table public.or_primary_evidence enable row level security;

create index if not exists idx_or_primary_evidence_candidate
  on public.or_primary_evidence(candidate_id, available_at desc);
create index if not exists idx_or_primary_evidence_snapshot
  on public.or_primary_evidence(evidence_snapshot_id);
create index if not exists idx_or_primary_evidence_symbol_cutoff
  on public.or_primary_evidence(symbol, evidence_cutoff desc, available_at desc);
create index if not exists idx_or_primary_evidence_source
  on public.or_primary_evidence(source_kind, available_at desc);
create index if not exists idx_or_primary_evidence_scan
  on public.or_primary_evidence(scan_id, source_kind);
