-- Oversold Reversion outcome tracking v1
-- Applied to Supabase project mnmkxjirpwbptdnvjmpw on 2026-08-18.

create table if not exists public.or_decision_tracks (
  id bigint generated by default as identity primary key,
  candidate_id bigint not null unique references public.or_candidates(id) on delete cascade,
  symbol text not null,
  name text,
  decision text not null check (decision in ('investigate','pass')),
  selected_at timestamptz not null,
  selected_price double precision not null check (selected_price > 0),
  selected_trade_ts timestamptz,
  session1_date date not null,
  session1_open timestamptz not null,
  session1_close timestamptz not null,
  session2_date date not null,
  session2_open timestamptz not null,
  session2_close timestamptz not null,
  active boolean not null default true,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.or_decision_tracks enable row level security;

create table if not exists public.or_track_checkpoints (
  id bigint generated by default as identity primary key,
  track_id bigint not null references public.or_decision_tracks(id) on delete cascade,
  session_no smallint not null check (session_no in (1,2)),
  checkpoint_kind text not null check (checkpoint_kind in ('open_plus_1h','mid_session','close')),
  scheduled_at timestamptz not null,
  status text not null default 'pending' check (status in ('pending','captured','missed','error')),
  captured_at timestamptz,
  bar_ts timestamptz,
  price double precision,
  return_pct double precision,
  error text,
  raw_bar jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(track_id, session_no, checkpoint_kind)
);
alter table public.or_track_checkpoints enable row level security;

create index if not exists idx_or_tracks_active_decision
  on public.or_decision_tracks(active, decision, selected_at desc);
create index if not exists idx_or_checkpoints_due
  on public.or_track_checkpoints(status, scheduled_at)
  where status='pending';
